spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

  sql:
    init:
      schema-locations:
        - classpath:sql/user/user_schema.sql
      mode: always

jwt:
  secret: ${JWT.SECRET}
  expirationInMs: 1800000 #30분
